### ISSUE TITLE
Test pipeline with GPUs using Singularity

### ISSUE THREAD

**Issue by drpatelh** [seqeralabs/nf-chai#6]
### Description of feature

As per [this comment](https://github.com/seqeralabs/nf-chai/pull/5#discussion_r1854546751) I added the `--nv` option to be set when running the pipeline with the `--use_gpus` parameter. We need to test this to ensure this is the correct default setting.

**Comment by drpatelh** [comment]
@FloWuenne you tested this setting with Apptainer and it was required right?

**Comment by FloWuenne** [comment]
Yes, this was tested and implemented for apptainer in #14 : https://github.com/seqeralabs/nf-chai/blob/17a6f52731ccc1e1257d8c92fa5cb895c06132c0/nextflow.config#L136

Singularity already has this option so should work just the same!
